[package]
name = "boom_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
prettytable-rs = "0.10.0"
sqlparser = "0.34.0"
